spring.application.name=ProjetoCrud

# Conexão com banco: SQL-TESTE
spring.datasource.url=jdbc:sqlserver://"NilpSQL**--01":1433;databaseName="10.0.70.88";encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=NilpSQL**--01
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
