spring.application.name=ProjetoCrud

# Conexão com banco: SQL-TESTE
spring.datasource.url=jdbc:sqlserver://10.0.70.88:1433;databaseName=Ecalc_teste;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=NilpSQL**--01
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
